### ISSUE TITLE
Support binary input

### ISSUE THREAD

**Issue by jdmeyer3** [3kwa/goingnats#1]
As part of my project, I need to be able to supply a byte string to NATs. When a byte string is supplied in this client, the NATs server is responding to the message
```
 cid:5 - Client parser ERROR, state=41, i=22: proto='"lo'\r\nCONNECT {\"name\": \"publisher"...'
```

This error was raised with the following code

```python
from goingnats import Client

with Client(name="publisher") as client:
    client.publish(subject="time.time", payload=b'hello')
```

The official NATs client requires the user to supply a byte string. I am very interested in using this library, but I would need the byte string support because I cannot convert it to a string. Would it be possible to support both string and byte string inputs?

**Comment by 3kwa** [comment]
Hi there, thanks for your interest, while it is possible to accept both bytes and string in theory, I'd rather support one or the other. Changing to bytes is possible but I am curious, why can't you `payload=b'hello'.decode()` when you publish?

**Comment by jdmeyer3** [comment]
I'm using compression on top of my messages for my particular use case. Decoding the string only causes errors for me. To give you an example of this
```python
import zlib 
from goingnats import Client

with Client(name="publisher") as client:
    client.publish(subject="time.time", payload=zlib.compress(b"hello"))
```

I understand if this is too much of an edge case, I was just hoping for parity between the official library and yours in terms of message input type. I also understand that changing the input to take byte string would be a breaking change.

**Comment by 3kwa** [comment]
Got it - let me look into it - I am not sure I am entirely happy with the tradeoffs str / bytes I made so happy to revisit.

**Comment by 3kwa** [comment]
version 2021.4.0 is bytes only for both subject and payload.

Take it for a spin and let me know if it does the trick!

**Comment by jdmeyer3** [comment]
Works like a charm, thank you for your responsiveness.
